"""ComfyUI本体に extra_model_paths.yaml を生成し、F:のモデル保管先を追加参照させる。

既存 ComfyUI_app/models/ の中身は一切移動・削除しない(追加参照のみ)。
既存の extra_model_paths.yaml がある場合は上書きせず、--force 指定時のみ
タイムスタンプ付きバックアップを取ってから置き換える。

  python scripts/setup_model_paths.py
  python scripts/setup_model_paths.py --force
"""
from __future__ import annotations
import argparse, json, shutil, sys, time
from pathlib import Path

sys.stdout.reconfigure(encoding='utf-8', errors='replace')  # P023

ROOT=Path(__file__).resolve().parents[1]
CFG=json.loads((ROOT/'config/settings.json').read_text(encoding='utf-8'))

# ComfyUIのフォルダ種別名 -> 保管先サブディレクトリ
SUBDIRS=['checkpoints','diffusion_models','text_encoders','clip','clip_vision','vae',
         'loras','upscale_models','controlnet','embeddings','unet','style_models']

def build_yaml(store:Path)->str:
    lines=['# Generated by services/comfyui_fullkit/scripts/setup_model_paths.py',
           '# 大容量モデルはF:に置き、ComfyUI本体からは追加検索パスとして参照する。',
           'clawstack_fullkit:',
           f'    base_path: {store.as_posix()}']
    lines+= [f'    {name}: {name}' for name in SUBDIRS]
    return '\n'.join(lines)+'\n'

def main()->int:
    p=argparse.ArgumentParser()
    p.add_argument('--force',action='store_true',help='既存yamlをバックアップして置き換える')
    a=p.parse_args()

    comfy=Path(CFG['comfyui_root'])
    if not (comfy/'main.py').exists():
        print('ComfyUI rootが不正です:',comfy); return 3
    store=Path(CFG.get('model_store_root') or (comfy/'models'))
    for name in SUBDIRS:
        (store/name).mkdir(parents=True,exist_ok=True)
    print('保管先を用意:',store)

    dst=comfy/'extra_model_paths.yaml'
    content=build_yaml(store)
    if dst.exists():
        if dst.read_text(encoding='utf-8')==content:
            print('既に同内容です:',dst); return 0
        if not a.force:
            print('既存ファイルがあります(上書きしません):',dst)
            print('置き換える場合は --force を付けて実行してください。'); return 4
        bak=dst.with_suffix(f'.yaml.bak_{time.strftime("%Y%m%d_%H%M%S")}')
        shutil.copy2(dst,bak); print('バックアップ:',bak)
    dst.write_text(content,encoding='utf-8')
    print('生成:',dst)
    print(content)
    return 0

if __name__=='__main__':
    raise SystemExit(main())
