const $=s=>document.querySelector(s);const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
async function api(url,opt={}){const r=await fetch(url,opt);if(!r.ok)throw new Error(await r.text());return r.json()}
document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>{document.querySelectorAll('nav button,.tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#tab-'+b.dataset.tab).classList.add('active');if(b.dataset.tab==='reviews')loadReviews();if(b.dataset.tab==='models')loadModels();if(b.dataset.tab==='metrics')loadMetrics()});
api('/api/health').then(x=>$('#health').textContent=`稼働中 / 外部API無効=${x.external_api_disabled}`).catch(()=>$('#health').textContent='接続エラー');
$('#inspect-form').onsubmit=async e=>{e.preventDefault();$('#inspect-message').textContent='検査中...';const fd=new FormData(e.target);try{const x=await api('/api/inspect',{method:'POST',body:fd});$('#inspect-message').textContent='完了';$('#result').innerHTML=`<div><div class="decision ${x.decision}">${x.decision}</div><p>異常スコア: ${x.anomaly_score.toFixed(5)}</p><p>${x.reasons.map(esc).join('<br>')}</p><p>モデル: ${esc(x.model_version)}</p><pre>${esc(JSON.stringify(x.measurements,null,2))}</pre><pre>${esc(JSON.stringify(x.elapsed_ms,null,2))}</pre></div><div><figure><figcaption>判定結果(NG箇所=赤枠)</figcaption><img src="${x.annotated_image_url}?t=${Date.now()}"></figure>${x.heatmap_image_url?`<figure><figcaption>異常ヒートマップ(青=正常/赤=異常)</figcaption><img src="${x.heatmap_image_url}?t=${Date.now()}"></figure>`:``}</div>`}catch(err){$('#inspect-message').textContent='失敗: '+err.message}};
async function loadReviews(){const status=$('#review-status').value;const rows=await api('/api/reviews?status='+encodeURIComponent(status));$('#reviews').innerHTML=rows.length?rows.map(r=>`<div class="review-card"><h3>${esc(r.product_id)} / AI=${esc(r.ai_decision)} / score=${Number(r.anomaly_score).toFixed(4)}</h3><p>${esc(r.ai_reason)}</p><div class="review-images"><img src="${r.original_url}"><img src="${r.annotated_url}"></div>${r.status==='PENDING'?`<div class="review-actions"><select id="d-${r.id}"><option>OK</option><option>NG</option></select><input id="m-${r.id}" placeholder="不良モード"><input id="c-${r.id}" placeholder="コメント"><button onclick="labelReview('${r.id}')">確定</button></div>`:`<p>確定=${esc(r.user_decision)} / ${esc(r.defect_mode)} / ${esc(r.comment)}</p>`}</div>`).join(''):'対象なし'}
window.labelReview=async id=>{await api(`/api/reviews/${id}/label`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({decision:$('#d-'+id).value,defect_mode:$('#m-'+id).value,comment:$('#c-'+id).value,use_for_training:true,reviewer:'local_user'})});loadReviews()};
async function loadModels(){const rows=await api('/api/models');$('#models').innerHTML=rows.map(m=>`<div class="model-card"><b>${esc(m.version)}</b> / ${esc(m.product_id)} / <b>${esc(m.stage)}</b><br>kind=${esc(m.kind)}<br>created=${esc(m.created_at)} ${m.stage!=='CHAMPION'?`<button onclick="promoteModel('${m.version}')">手動昇格</button>`:''}</div>`).join('')||'モデルなし'}
window.promoteModel=async v=>{if(!confirm(`${v} をChampionへ昇格しますか？`))return;await api(`/api/models/${v}/promote`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({confirm:true,approved_by:'local_user',note:'UI manual approval'})});loadModels()};
async function loadMetrics(){$('#metrics').textContent=JSON.stringify(await api('/api/metrics'),null,2)}
$('#reload-reviews').onclick=loadReviews;$('#review-status').onchange=loadReviews;$('#reload-models').onclick=loadModels;$('#reload-metrics').onclick=loadMetrics;
$('#train-reference').onclick=async()=>{await api('/api/learning/reference?product_id=demo_press_part',{method:'POST'});alert('候補学習を登録しました。自動昇格はしません。');setTimeout(loadModels,2500)};
