#!/usr/bin/env python3
"""Render time-varying virtual risk animations from OpenFOAM VTK snapshots."""
from __future__ import annotations
import argparse, json, subprocess
from pathlib import Path
import numpy as np
import pyvista as pv

def main() -> int:
    ap=argparse.ArgumentParser(); ap.add_argument('--series',type=Path,required=True); ap.add_argument('--quality',type=Path,required=True); ap.add_argument('--out',type=Path,required=True); ap.add_argument('--case',default='box100x60x50')
    a=ap.parse_args(); out=a.out.resolve(); out.mkdir(parents=True,exist_ok=True)
    series=json.loads(a.series.read_text())['files']
    # The corrected fill reaches >99% by about 0.5 s.  Use every early solver
    # snapshot so the front motion is not lost by coarse frame decimation.
    selected=[x for x in series if float(x['time']) <= 0.5]
    if selected[-1]['name'] != series[-1]['name']: selected.append(series[-1])
    base=pv.read(a.quality); names=['warpage','sink','weld','airtrap','void']
    surfaces={n:base.extract_surface() for n in names}
    # Keep camera and scalar range identical across frames.
    for n in names:
        frames=[]
        accumulated=np.zeros(base.n_cells,dtype=float)
        for i,item in enumerate(selected):
            # The converter emits both case_N.vtm and case_N/internal.vtu.
            internal=a.series.parent/Path(item['name']).stem/'internal.vtu'
            snap=pv.read(internal); alpha=np.asarray(snap.cell_data['alpha.polymer'],float)
            g=base.copy()
            # These are visual, dimensionless screening fields.  Their explicit
            # alpha dependence makes the advancing front visible; they are not
            # calibrated displacement, depth, strength, or void predictions.
            if n in ('airtrap','void'):
                # Keep candidate markers after the front passes.  A completed
                # fill is not evidence that an air/void candidate never
                # existed.  For virtual screening we combine the transient
                # unfilled-front marker with the mechanism fields generated by
                # derive_void_mechanisms.py.  This is deliberately a visible
                # candidate map, not a calibrated defect probability.
                pressure=np.asarray(base.cell_data.get('pressure_MPa_calibrated',np.full(base.n_cells,1.0)),float)
                distance_marker=np.clip(1-alpha,0,1)
                low_pressure_marker=np.clip((0.5-pressure)/0.5,0,1)
                if n == 'airtrap':
                    mechanism=np.asarray(base.cell_data.get('void_air_entrapment_risk',np.zeros(base.n_cells)),float)
                    centers=np.asarray(base.cell_centers().points)
                    xspan=max(float(np.ptp(centers[:,0])),1e-12)
                    vent_distance=np.clip((centers[:,0]-float(centers[:,0].min()))/xspan,0,1)
                    far_end=np.clip((vent_distance-0.60)/0.40,0,1)
                    candidate=np.clip(0.70*distance_marker*far_end + 0.25*mechanism + 0.10*low_pressure_marker,0,1)
                else:
                    pvt=np.asarray(base.cell_data.get('void_pvt_shrink_void_risk',np.zeros(base.n_cells)),float)
                    underpack=np.asarray(base.cell_data.get('void_underpack_risk',np.zeros(base.n_cells)),float)
                    thick=np.asarray(base.cell_data.get('void_thick_section_risk',np.zeros(base.n_cells)),float)
                    candidate=np.clip(0.55*pvt + 0.25*underpack + 0.20*thick,0,1)
                accumulated=np.maximum(accumulated,candidate)
                field=accumulated
            elif n=='weld':
                instantaneous=np.clip(4*alpha*(1-alpha)*np.asarray(base.cell_data['weld_risk_proxy']) + 0.15*alpha*(1-alpha),0,1)
                accumulated=np.maximum(accumulated,instantaneous)
                field=accumulated
            elif n=='sink': field=np.clip(np.asarray(base.cell_data['sink_risk_proxy'])*(0.05+0.95*alpha),0,1)
            else: field=np.clip(np.asarray(base.cell_data['warpage_risk_proxy'])*(0.05+0.95*alpha),0,1)
            g.cell_data['anim_field']=field.astype(np.float32)
            p=pv.Plotter(off_screen=True,window_size=(1400,800)); p.set_background('white')
            p.add_mesh(g.extract_surface(),scalars='anim_field',cmap='turbo',clim=(0,1),scalar_bar_args={'title':'Relative risk 0-1'})
            p.view_xy(); p.camera.roll=90; p.camera.zoom(1.15)
            p.add_text(f'{a.case} {n} | t={item["time"]:.2f} s | VIRTUAL SCREENING ONLY',color='black',font_size=18)
            fn=out/f'{n}_{i:03d}.png'; p.screenshot(fn); p.close(); frames.append(fn)
        mp4=out/f'{a.case}_{n}_virtual_animation.mp4'
        subprocess.run(['ffmpeg','-y','-loglevel','error','-framerate','4','-i',str(out/f'{n}_%03d.png'),'-pix_fmt','yuv420p',str(mp4)],check=True)
        for f in frames: f.unlink()
    (out/'animation_manifest.json').write_text(json.dumps({'status':'ANIMATED_FROM_OPENFOAM_TIME_SERIES','frames':len(selected),'videos':[str(x) for x in out.glob('*.mp4')]},indent=2)+'\n')
    print(json.dumps({'frames':len(selected),'out':str(out)},indent=2)); return 0
if __name__=='__main__': raise SystemExit(main())
